version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@nl-rvo/assets"
      - dependency-name: "@nl-rvo/component-library-css"
      - dependency-name: "@nl-rvo/design-tokens"
